[theme]
primaryColor = "#EA6FA8"
backgroundColor = "#FFF9EE"
secondaryBackgroundColor = "#FDECF3"
textColor = "#403747"


font = "Pixelify Sans:https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap, sans-serif"